//2020
CREATE SCHEMA `project-8e2366a6-d3cc-40ee-9de.external_dataset`
OPTIONS (
  location = 'asia-southeast1'
);

CREATE OR REPLACE EXTERNAL TABLE
`project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2020`
OPTIONS (
  format = 'PARQUET',
  uris = [
    'gs://project-8e2366a6-d3cc-40ee-9de-silver-curated-dev/ahrf/hospital_resources/ahrf_silver_2020.parquet'
  ]
);

MERGE `project-8e2366a6-d3cc-40ee-9de.hospital_dwh_dev.dim_population` AS target

USING (
    SELECT
        CONCAT(
            LPAD(CAST(fips_st AS STRING), 2, '0'),
            LPAD(CAST(fips_cnty AS STRING), 3, '0')
        ) AS county_fips,
        2020 AS census_year,
        SAFE_CAST(physicians_20 AS FLOAT64) AS physicians_per_100k
    FROM `project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2020`
) AS source
ON target.county_fips = source.county_fips
AND target.census_year = source.census_year
WHEN MATCHED THEN

UPDATE SET
    target.physicians_per_100k = source.physicians_per_100k;

UPDATE `project-8e2366a6-d3cc-40ee-9de.hospital_dwh_dev.dim_population` t
SET nurses_per_100k = s.nurses_per_100k
FROM (
SELECT
CONCAT(
LPAD(CAST(fips_st AS STRING), 2, '0'),
LPAD(CAST(fips_cnty AS STRING), 3, '0')
) AS county_fips,
2020 AS census_year,
SAFE_CAST(nurse_20 AS FLOAT64) AS nurses_per_100k
FROM `project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2020`
) s
WHERE t.county_fips = s.county_fips
AND t.census_year = s.census_year;

//2021
CREATE OR REPLACE EXTERNAL TABLE
`project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2021`
OPTIONS (
  format = 'PARQUET',
  uris = [
    'gs://project-8e2366a6-d3cc-40ee-9de-silver-curated-dev/ahrf/hospital_resources/ahrf_silver_2021.parquet'
  ]
);

MERGE `project-8e2366a6-d3cc-40ee-9de.hospital_dwh_dev.dim_population` AS target

USING (
    SELECT
        CONCAT(
            LPAD(CAST(fips_st AS STRING), 2, '0'),
            LPAD(CAST(fips_cnty AS STRING), 3, '0')
        ) AS county_fips,
        2021 AS census_year,
        SAFE_CAST(physicians_21 AS FLOAT64) AS physicians_per_100k
    FROM `project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2021`
) AS source

ON target.county_fips = source.county_fips
AND target.census_year = source.census_year
WHEN MATCHED THEN
UPDATE SET
    target.physicians_per_100k = source.physicians_per_100k;

UPDATE `project-8e2366a6-d3cc-40ee-9de.hospital_dwh_dev.dim_population` t
SET nurses_per_100k = s.nurses_per_100k
FROM (
SELECT
CONCAT(
LPAD(CAST(fips_state_code AS STRING), 2, '0'),
LPAD(CAST(fips_conty_code AS STRING), 3, '0')
) AS county_fips,
2021 AS census_year,
SAFE_CAST(nurse_21 AS FLOAT64) AS nurses_per_100k
FROM `project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2021`
) s
WHERE t.county_fips = s.county_fips
AND t.census_year = s.census_year;

//2022
CREATE OR REPLACE EXTERNAL TABLE
`project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2022`
OPTIONS (
  format = 'PARQUET',
  uris = [
    'gs://project-8e2366a6-d3cc-40ee-9de-silver-curated-dev/ahrf/hospital_resources/ahrf_silver_2022.parquet'
  ]
);

MERGE `project-8e2366a6-d3cc-40ee-9de.hospital_dwh_dev.dim_population` AS target
USING (
    SELECT
        CONCAT(
            LPAD(CAST(fips_st AS STRING), 2, '0'),
            LPAD(CAST(fips_cnty AS STRING), 3, '0')
        ) AS county_fips,
        2022 AS census_year,
        SAFE_CAST(physicians_22 AS FLOAT64) AS physicians_per_100k
    FROM `project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2022`
) AS source
ON target.county_fips = source.county_fips
AND target.census_year = source.census_year
WHEN MATCHED THEN
UPDATE SET
    target.physicians_per_100k = source.physicians_per_100k;

UPDATE `project-8e2366a6-d3cc-40ee-9de.hospital_dwh_dev.dim_population` t
SET nurses_per_100k = s.nurses_per_100k
FROM (
SELECT
CONCAT(
LPAD(CAST(fips_state_code AS STRING), 2, '0'),
LPAD(CAST(fips_conty_code AS STRING), 3, '0')
) AS county_fips,
2022 AS census_year,
SAFE_CAST(nurse_22 AS FLOAT64) AS nurses_per_100k
FROM `project-8e2366a6-d3cc-40ee-9de.external_dataset.dim_resources_2022`
) s
WHERE t.county_fips = s.county_fips
AND t.census_year = s.census_year;

