config {
  type: "incremental",
  name: "fact_hospital_utilization",
  description: "Bảng Fact cốt lõi lưu trữ mức độ sử dụng tài nguyên bệnh viện",
  uniqueKey: ["fact_id"], 
  bigquery: {
    partitionBy: "report_date",
    clusterBy: ["hospital_id", "source_id"],
    requirePartitionFilter: true, // CRITICAL: Chặn Looker Studio full table scan
    
    // Idempotent filter: Base on execution_date, NOT CURRENT_DATE()
    updatePartitionFilter: `report_date >= DATE_SUB(DATE('${dataform.projectConfig.vars.execution_date}'), INTERVAL 14 DAY)`
  },
  tags: ["daily_run", "fact", "core"],
  assertions: {
    uniqueKey: ["fact_id"],
    nonNull: ["fact_id", "hospital_id", "report_date"]
  }
}

SELECT
  hospital_id , 
  collection_week, 
  inpatient_beds_capacity, 
  inpatient_beds_used, 
  icu_beds_capacity, 
  icu_beds_used, 
  covid_hospitalized_patients, 
  covid_icu_patients, 
  influenza_hospitalized_patients, 
  influenza_icu_patients, 
  ed_visits_total, 
  covid_admissions_adult, 
  covid_admissions_pediatric, 
  pediatric_beds_capacity, 
  pediatric_beds_used, 
  state, 
  is_corrected, 
  inpatient_occupancy_rate, 
  icu_occupancy_rate, 
  overload_flag,
  CURRENT_TIMESTAMP() AS dwh_updated_at, -- Đổi tên cho rõ nghĩa là thời điểm BQ merge
  pipeline_version
FROM
  ${ref("stg_fact_hospital_utilization")}