config {
  type: "view",
  schema: "hospital_staging",
  name: "stg_dim_geography",
  description: "Staging cho Dimension Địa lý. Lọc lấy batch dữ liệu mới nhất từ GCS.",
  tags: ["daily_run", "staging"]
}

SELECT
  TRIM(county_fips) AS county_fips,
  TRIM(county_name) AS county_name,
  TRIM(UPPER(state_code)) AS state_code,
  TRIM(state_name) AS state_name,
  COALESCE(TRIM(hrr_region), 'Unknown') AS hrr_region,
  COALESCE(area_km2, 0.0) AS area_km2
FROM
  ${ref("ext_dim_geography")}
WHERE
  -- dataform.projectConfig.vars.data_date được Airflow truyền vào dạng YYYY-MM-DD
  exec_date = '${dataform.projectConfig.vars.data_date}'