# workflow_settings.yaml
dataformCoreVersion: 3.0.56
defaultProject: "project-8e2366a6-d3cc-40ee-9de"
defaultLocation: "asia-southeast1"
defaultDataset: "hospital_dwh"
defaultAssertionDataset: "data_assertions"

datasetSuffix: "dev"

vars:
  env: "dev"
  staging_dataset: "hospital_staging_dev"
  execution_date: "1970-01-01"
