# -*- coding: utf-8 -*-
"""census|ahrf_bigdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eyZRXb_P3euHJ5CDTffUK5gUZyGk02io
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""CENSUS ACS"""

# import pandas as pd

# # Link API
# url_2020 = "https://api.census.gov/data/2020/acs/acs5?get=NAME,B01003_001E&for=county:*&in=state:*&key=937589a4e18bf415305ccf41b6e8aa6ee0fcc258"
# url_2021 = "https://api.census.gov/data/2021/acs/acs5?get=NAME,B01003_001E&for=county:*&in=state:*&key=937589a4e18bf415305ccf41b6e8aa6ee0fcc258"
# url_2022 = "https://api.census.gov/data/2022/acs/acs5?get=NAME,B01003_001E&for=county:*&in=state:*&key=937589a4e18bf415305ccf41b6e8aa6ee0fcc258"
# url_2023 = "https://api.census.gov/data/2023/acs/acs5?get=NAME,B01003_001E&for=county:*&in=state:*&key=937589a4e18bf415305ccf41b6e8aa6ee0fcc258"
# url_2024 = "https://api.census.gov/data/2024/acs/acs5?get=NAME,B01003_001E&for=county:*&in=state:*&key=937589a4e18bf415305ccf41b6e8aa6ee0fcc258"

# # Đọc dữ liệu JSON từ API
# df_r2020 = pd.read_json(url_2020)
# df_r2021 = pd.read_json(url_2021)
# df_r2022 = pd.read_json(url_2022)
# df_r2023 = pd.read_json(url_2023)
# df_r2024 = pd.read_json(url_2024)

# def preprocess_data(df):
#     # Dòng đầu tiên đang là header -> chuyển thành tên cột
#     df.columns = df.iloc[0]

#     # Bỏ dòng header cũ
#     df = df[1:].reset_index(drop=True)

#     # Tách cột NAME thành county_name và state_name
#     df[['county_name', 'state_name']] = df['NAME'].str.split(', ', expand=True)


#     # === NHIỆM VỤ 1: ĐỔI TÊN CỘT ===
#     # Dùng dictionary để ánh xạ tên cũ thành tên mới
#     df = df.rename(columns={
#         'B01003_001E': 'total_pop',
#         'state': 'state_fips',
#         'county': 'county_fips'
#     })


#     # === NHIỆM VỤ 2: SẮP XẾP LẠI THỨ TỰ CỘT ===
#     # Khai báo danh sách các cột theo thứ tự mong muốn
#     new_order = ['state_fips', 'state_name', 'county_fips', 'county_name', 'total_pop']

#     # Áp dụng thứ tự mới vào DataFrame
#     df = df[new_order]
#     return df

# df_census_2020 = preprocess_data(df_r2020)
# df_census_2021 = preprocess_data(df_r2021)
# df_census_2022 = preprocess_data(df_r2022)
# df_census_2023 = preprocess_data(df_r2023)
# df_census_2024 = preprocess_data(df_r2024)

"""AHRF"""

#!pip install pyreadstat

# #NĂM 2020
# import pyreadstat
# import re

# # =========================
# # 1. Hàm parse tên biến từ file .sas năm 2021
# # =========================

# def extract_column_names_from_sas(sas_file_path):

#     names = []

#     with open(sas_file_path, 'r', encoding='latin1') as f:
#         lines = f.readlines()

#     for line in lines:

#         line = line.strip()

#         match = re.search(
#             r'@(\d+)\s+([A-Za-z0-9_]+)\s+\$?\s*([0-9]+)\.\s*/\*(.*?)\*/',
#             line
#         )

#         if match:

#             description = match.group(4).strip()

#             # clean tên cột
#             description = re.sub(r'\s+', '_', description)
#             description = re.sub(r'[^A-Za-z0-9_]', '', description)

#             names.append(description)

#     # xử lý duplicated names
#     seen = {}
#     clean_names = []

#     for name in names:

#         if name in seen:
#             seen[name] += 1
#             name = f"{name}_{seen[name]}"
#         else:
#             seen[name] = 0

#         clean_names.append(name)

#     return clean_names


# # =========================
# # 2. Đọc file SAS7BDAT năm 2020
# # =========================

# ahrf_2020_path = "/content/drive/MyDrive/BD_ahrf_data/ahrf2020.sas7bdat"
# df_ahrf_2020, meta = pyreadstat.read_sas7bdat(ahrf_2020_path)

# print("Shape before rename:", df_ahrf_2020.shape)


# # =========================
# # 3. Lấy header thật từ file .sas năm 2021
# # =========================

# sas_2021_path = "/content/drive/MyDrive/BD_ahrf_data/AHRF2020-2021.sas"

# real_headers = extract_column_names_from_sas(sas_2021_path)

# print("Number of parsed headers:", len(real_headers))
# print(real_headers[:10])


# # =========================
# # 4. Map header f00001 -> tên thật
# # =========================

# # đảm bảo số cột khớp
# min_cols = min(len(df_ahrf_2020.columns), len(real_headers))

# rename_dict = {
#     old_col: real_headers[i]
#     for i, old_col in enumerate(df_ahrf_2020.columns[:min_cols])
# }

# df_ahrf_2020 = df_ahrf_2020.rename(columns=rename_dict)


# # =========================
# # 5. Kiểm tra kết quả
# # =========================

# print(df_ahrf_2020.columns[:20])

# df_ahrf_2020.head()

# #NĂM 2021 + 2022
# ahrf_2021_sas = "/content/drive/MyDrive/BD_ahrf_data/AHRF2020-2021.sas"
# ahrf_2022_sas = "/content/drive/MyDrive/BD_ahrf_data/AHRF2021-2022.sas"

# ahrf_2021_asc = "/content/drive/MyDrive/BD_ahrf_data/ahrf2021.asc"
# ahrf_2022_asc = "/content/drive/MyDrive/BD_ahrf_data/ahrf2022.asc"

# import pandas as pd
# import re

# def convert_sas_to_asc(sas_file_path, asc_file_path):

#     colspecs = []
#     names = []

#     with open(sas_file_path, 'r', encoding='latin1') as f:
#         lines = f.readlines()

#     for line in lines:

#         line = line.strip()

#         match = re.search(
#             r'@(\d+)\s+([A-Za-z0-9_]+)\s+\$?\s*([0-9]+)\.\s*/\*(.*?)\*/',
#             line
#         )

#         if match:

#             start = int(match.group(1))
#             width = int(match.group(3))

#             # lấy phần mô tả trong comment
#             description = match.group(4).strip()

#             # làm sạch tên cột
#             description = re.sub(r'\s+', '_', description)
#             description = re.sub(r'[^A-Za-z0-9_]', '', description)

#             colspecs.append((start - 1, start - 1 + width))
#             names.append(description)

#     #xử lý duplicated name
#     seen = {}

#     clean_names = []

#     for name in names:

#         if name in seen:
#             seen[name] += 1
#             name = f"{name}_{seen[name]}"
#         else:
#             seen[name] = 0

#         clean_names.append(name)

#     names = clean_names
#     print(f"Parsed {len(names)} columns")

#     df = pd.read_fwf(
#         asc_file_path,
#         colspecs=colspecs,
#         names=names,
#         dtype=str,
#         encoding='latin1', # Added encoding='latin1' here
#     )

#     return df

# df_ahrf_2021 = convert_sas_to_asc(ahrf_2021_sas, ahrf_2021_asc)
# df_ahrf_2021.head()

# df_ahrf_2022 = convert_sas_to_asc(ahrf_2022_sas, ahrf_2022_asc)
# df_ahrf_2022.head()

#NĂM 2023 2024 2025
ahrf_2023_path = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2023.csv"
ahrf_2024_path = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2024.csv"
ahrf_2025_path = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2025.csv"

df_ahrf_2023 = pd.read_csv(ahrf_2023_path, encoding='latin1', low_memory=False)
df_ahrf_2024 = pd.read_csv(ahrf_2024_path, encoding='latin1', low_memory= False)
df_ahrf_2025 = pd.read_csv(ahrf_2025_path, encoding='latin1', low_memory= False)

"""ĐẨY LÊN GCS"""

#gs://healthcare-data-lake/bronze/census/year=2020/census_2020.parquet

PROJECT_ID = "project-8e2366a6-d3cc-40ee-9de"

#BUCKET_NAME = "project-8e2366a6-d3cc-40ee-9de-bronze-raw-dev"

#!pip install gcsfs pyarrow

from google.colab import auth
auth.authenticate_user()

from google.cloud import storage

client = storage.Client()
bucket = client.bucket("project-8e2366a6-d3cc-40ee-9de-bronze-raw-dev")

def upload_df_to_bronze(df, local_file, gcs_path):

    # save parquet
    df.to_parquet(local_file, index=False)

    # upload
    blob = bucket.blob(gcs_path)
    blob.upload_from_filename(local_file)

    print(f"Uploaded to gs://data-bronze/{gcs_path}")

#đẩy census lên bronze
# datasets = [
#     (
#         df_census_2020,
#         "census_2020.parquet",
#         "population/census_acs/census_2020.parquet"
#     ),

#     (
#         df_census_2021,
#         "census_2021.parquet",
#         "population/census_acs/census_2021.parquet"
#     ),
#     (
#         df_census_2022,
#         "census_2022.parquet",
#         "population/census_acs/census_2022.parquet"
#     ),
#     (
#         df_census_2023,
#         "census_2023.parquet",
#         "population/census_acs/census_2023.parquet"
#     ),
#     (
#         df_census_2024,
#         "census_2024.parquet",
#         "population/census_acs/census_2024.parquet"
#     )
# ]

# for df, local_file, gcs_path in datasets:
#     upload_df_to_bronze(df, local_file, gcs_path)

# #đẩy ahrf lên bronze
# datasets = [
#     (
#         df_ahrf_2020,
#         "ahrf_2020.parquet",
#         "ahrf/hospital_resources/ahrf_2020.parquet"
#     ),

#     (
#         df_ahrf_2021,
#         "ahrf_2021.parquet",
#         "ahrf/hospital_resources/ahrf_2021.parquet"
#     ),
#     (
#         df_ahrf_2022,
#         "ahrf_2022.parquet",
#         "ahrf/hospital_resources/ahrf_2022.parquet"
#     )
# ]

# for df, local_file, gcs_path in datasets:
#     upload_df_to_bronze(df, local_file, gcs_path)

# #đẩy ahrf lên bronze
# datasets = [
#     (
#         df_ahrf_2020,
#         "ahrf_2020.parquet",
#         "ahrf/hospital_resources/ahrf_2020.parquet"
#     ),

#     (
#         df_ahrf_2021,
#         "ahrf_2021.parquet",
#         "ahrf/hospital_resources/ahrf_2021.parquet"
#     ),
#     (
#         df_ahrf_2022,
#         "ahrf_2022.parquet",
#         "ahrf/hospital_resources/ahrf_2022.parquet"
#     )
# ]

# for df, local_file, gcs_path in datasets:
#     upload_df_to_bronze(df, local_file, gcs_path)

#đẩy ahrf lên bronze
datasets = [
     (
         df_ahrf_2023,
         "ahrf_2023.parquet",
         "ahrf/hospital_resources/ahrf_2023.parquet"
     ),

     (
         df_ahrf_2024,
         "ahrf_2024.parquet",
         "ahrf/hospital_resources/ahrf_2024.parquet"
     ),
     (
         df_ahrf_2025,
         "ahrf_2025.parquet",
         "ahrf/hospital_resources/ahrf_2025.parquet"
     )
 ]

for df, local_file, gcs_path in datasets:
    upload_df_to_bronze(df, local_file, gcs_path)

"""XONG INGESTION LÊN BRONZE"""