# -*- coding: utf-8 -*-
"""ahrf_bronze_to_silver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5Wr75iN-FHbmGBeQyccoqLakBKBTapM
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#!pip install pyreadstat

#NĂM 2020
import pyreadstat
import re

# =========================
# 1. Đọc file SAS7BDAT năm 2020
# =========================

ahrf_2020_path = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2020.sas7bdat"
df_ahrf_2020, meta = pyreadstat.read_sas7bdat(ahrf_2020_path)


# =========================
# 2. Kiểm tra kết quả
# =========================

print(df_ahrf_2020.columns[:20])

df_ahrf_2020.head()

#NĂM 2021 + 2022
ahrf_2021_sas = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2021.sas"
ahrf_2022_sas = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2022.sas"

ahrf_2021_asc = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2021.asc"
ahrf_2022_asc = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2022.asc"

# import pandas as pd
# import re

# def convert_sas_to_asc(sas_file_path, asc_file_path):

#     colspecs = []
#     names = []

#     with open(sas_file_path, 'r', encoding='latin1') as f:
#         lines = f.readlines()

#     for line in lines:

#         line = line.strip()

#         match = re.search(
#             r'@(\d+)\s+([A-Za-z0-9_]+)\s+\$?\s*([0-9]+)\.\s*/\*(.*?)\*/',
#             line
#         )

#         if match:

#             start = int(match.group(1))
#             width = int(match.group(3))

#             # # lấy phần mô tả trong comment
#             # description = match.group(4).strip()

#             # # làm sạch tên cột
#             # description = re.sub(r'\s+', '_', description)
#             # description = re.sub(r'[^A-Za-z0-9_]', '', description)

#             colspecs.append((start - 1, start - 1 + width))
#            # names.append(description)

#     #xử lý duplicated name
#     seen = {}

#     clean_names = []

#     for name in names:

#         if name in seen:
#             seen[name] += 1
#             name = f"{name}_{seen[name]}"
#         else:
#             seen[name] = 0

#         clean_names.append(name)

#     names = clean_names
#     print(f"Parsed {len(names)} columns")

#     df = pd.read_fwf(
#         asc_file_path,
#         #colspecs=colspecs,
#         #names=names,
#         dtype=str,
#         encoding='latin1', # Added encoding='latin1' here
#     )

#     return df

import re

def convert_sas_to_asc(sas_file_path, asc_file_path):
    colspecs = []
    names = []

    with open(sas_file_path , 'r', encoding='latin1') as f:
        lines = f.readlines()

    for line in lines:
        match = re.search(r'@(\d+)\s+(\w+)\s+\$?(\d+)\.', line)

        if match:
            start = int(match.group(1))
            name = match.group(2)
            width = int(match.group(3))

            colspecs.append((start-1, start-1+width))
            names.append(name)

    df = pd.read_fwf(
        asc_file_path,
        colspecs=colspecs,
        names=names,
        encoding = 'latin1'
    )

    return df

df_ahrf_2021 = convert_sas_to_asc(ahrf_2021_sas, ahrf_2021_asc)
df_ahrf_2022 = convert_sas_to_asc(ahrf_2022_sas, ahrf_2022_asc)

df_ahrf_2021.head()

# # tên cột cần tìm
# col_name = 'fips_cnty'#'fips_st'#'st_name', 'cnty_name'



# # kiểm tra cột có tồn tại không
# if col_name in df_ahrf_2024.columns:
#     print("Cột tồn tại")

#     # xem kiểu dữ liệu của cột
#     print(df_ahrf_2024[col_name].dtype)
# else:
#     print("Không tìm thấy cột")

#NĂM 2023 2024 2025
ahrf_2023_path = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2023.csv"
ahrf_2024_path = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2024.csv"
ahrf_2025_path = "/content/drive/MyDrive/UET của Pling /[NĂM  3] HỌC KỲ II/big data/BIGDATA_NHÓM 4/ahrf/ahrf2025.csv"

df_ahrf_2023 = pd.read_csv(ahrf_2023_path, encoding='latin1', low_memory=False)
df_ahrf_2024 = pd.read_csv(ahrf_2024_path, encoding='latin1', low_memory= False)
df_ahrf_2025 = pd.read_csv(ahrf_2025_path, encoding='latin1', low_memory= False)

df_ahrf_2024.head()

"""CHUẨN HOÁ"""

# 2020
# Danh sách các cột cần lấy từ ảnh
# cols = [
#     'f14642',
#     'f14646',
#     'f14643',
#     'f14645',
#     'f11308',
#     'f12645',
#     'f12646',
#     'f12653',
#     'f12654',
#     'f14794',
#     'f14795'
# ]

# # Get columns that exist in df_ahrf_2020
# existing_cols = [col for col in cols if col in df_ahrf_2021.columns]
# missing_cols = [col for col in cols if col not in df_ahrf_2021.columns]

# if missing_cols:
#     print(f"Lỗi: Các cột sau không được tìm thấy trong df_ahrf_2021: {missing_cols}")
#     print("Vui lòng kiểm tra lại tên cột hoặc các năm của dữ liệu.")
#     print("Các cột có sẵn trong df_ahrf_2021 là:")
#     print(df_ahrf_2021.columns.tolist())
# else:
#     # Copy các cột từ df_ahrf_2021 sang df_using_2021
#     df_using_2021 = df_ahrf_2021[cols].copy()
#     print("Đã tạo df_using_2021 với tất cả các cột được yêu cầu.")

#2020
cols = [
    'f00008', 'f00010', 'f00011', 'f00012',
    'f1130818', # # FTE Physicians & Dentists
    'f1464619' # Adv Practice Regist Nurse w/NPI
]

# Copy các cột từ df_ahrf_2020 sang df_using_2020
df_use_ahrf_2020 = df_ahrf_2020[cols].copy()
# Đổi tên cột
df_use_ahrf_2020.rename(
    columns={
        'f00008': 'state_name',
        'f00010': 'county_name',
        'f00011': 'fips_st',
        'f00012': 'fips_cnty',
        'f1130818': 'physicians_20',
        'f1464619': 'nurse_20'
    },
    inplace=True
)
df_use_ahrf_2020.head()

#2021
cols1 = [
    'f1130819',  # FTE Physicians & Dentists
    'f1464620'   # Adv Practice Regist Nurse w/NPI
]

cols2 = [
    'f00008',
    'f00010',
    'f00011',
    'f00012'
]

# lấy info định danh từ 2020
base_2020 = df_ahrf_2020[cols2].copy()

# lấy dữ liệu physician/nurse từ 2021
data_2021 = df_ahrf_2021[cols1].copy()

# join theo index
df_use_ahrf_2021 = base_2020.join(data_2021)

# rename
df_use_ahrf_2021.rename(
    columns={
        'f00008': 'state_name',
        'f00010': 'county_name',
        'f00011': 'fips_state_code',
        'f00012': 'fips_county_code',
        'f1130819': 'physicians_21',
        'f1464620': 'nurse_21'
    },
    inplace=True
)

df_use_ahrf_2021.head()

#2022
cols1 = [
    'f1130820', # FTE Physicians & Dentists
    'f1464621'  #Adv Practice Regist Nurse w/NPI
]

cols2 = [
    'f00008',
    'f00010',
    'f00011',
    'f00012'
]

# lấy info định danh từ 2020
base_2020 = df_ahrf_2020[cols2].copy()

# lấy dữ liệu physician/nurse từ 2021
data_2022 = df_ahrf_2022[cols1].copy()

# join theo index
df_use_ahrf_2022 = base_2020.join(data_2022)

df_use_ahrf_2022.rename(
    columns={
        'f00008': 'state_name',
        'f00010': 'county_name',
        'f00011': 'fips_state_code',
        'f00012': 'fips_county_code',
        'f1130820': 'physicians_22',
        'f1464621': 'nurse_22'
    },
    inplace=True
)
df_use_ahrf_2022.head()

#2023
cols = [
    'st_name',
    'cnty_name',
    'fips_st',
    'fips_cnty',
    'stgh_fte_phys_dent_incl_nh_21',
    'stgh_rn_ft_incl_nh_21', 'aprn_npi_22'
]

# Copy các cột từ df_ahrf_2020 sang df_using_2020
df_use_ahrf_2023 = df_ahrf_2023[cols].copy()

# Tạo cột nurse_23 = tổng 2 cột nurse
df_use_ahrf_2023['nurse_23'] = (
    df_use_ahrf_2023['stgh_rn_ft_incl_nh_21'] +
    df_use_ahrf_2023['aprn_npi_22']
)

# Đổi tên cột physician
df_use_ahrf_2023.rename(
    columns={
        'stgh_fte_phys_dent_incl_nh_21': 'physicians_23'
    },
    inplace=True
)

df_use_ahrf_2023 = df_use_ahrf_2023[
    ['st_name',
    'cnty_name',
    'fips_st',
    'fips_cnty','physicians_23', 'nurse_23']
]

df_use_ahrf_2023.head()

#2024
cols = [
    'st_name', 'cnty_name', 'fips_cnty', 'fips_st',
    'phys_nf_prim_care_pc_exc_rsdt_22',
    'aprn_npi_23'

]
# Copy các cột từ df_ahrf_2020 sang df_using_2020
df_use_ahrf_2024 = df_ahrf_2024[cols].copy()
# Đổi tên cột
df_use_ahrf_2024.rename(
    columns={
        'phys_nf_prim_care_pc_exc_rsdt_22': 'physicians_24',
        'aprn_npi_23': 'nurse_24'
    },
    inplace=True
)
df_use_ahrf_2024.head()

#2025
cols = [
    'st_name', 'cnty_name', 'fips_cnty', 'fips_st',
    'stgh_rn_ft_incl_nh_23',
    'aprn_npi_24'
]
# Copy các cột từ df_ahrf_2020 sang df_using_2020
df_use_ahrf_2025 = df_ahrf_2025[cols].copy()

# Đổi tên cột
df_use_ahrf_2025.rename(
    columns={
        'stgh_rn_ft_incl_nh_23': 'physicians_25',
        'aprn_npi_24': 'nurse_25'
    },
    inplace=True
)
df_use_ahrf_2025.head()

print(df_use_ahrf_2023.dtypes)

def preprocessing(df_silver):

    numeric_cols = df_silver.select_dtypes(
        exclude=['object']
    ).columns

    for col in numeric_cols:

        df_silver[col] = (
            df_silver[col]
            .astype(str)
            .str.strip()
            .str.replace(',', '', regex=False)
            .str.replace(r'[^0-9.\-]', '', regex=True)
        )

        df_silver[col] = pd.to_numeric(
            df_silver[col],
            errors='coerce'
        ).astype(float)

    return df_silver

df_silver_2020 = preprocessing(df_use_ahrf_2020)
df_silver_2021 = preprocessing(df_use_ahrf_2021)
df_silver_2022 = preprocessing(df_use_ahrf_2022)
df_silver_2023 = preprocessing(df_use_ahrf_2023)
df_silver_2024 = preprocessing(df_use_ahrf_2024)
df_silver_2025 = preprocessing(df_use_ahrf_2025)
# Kiểm tra datatype
print(df_silver_2023.dtypes)

# Preview dữ liệu
df_silver_2023.head()

def drop_high_null_columns(df, threshold=80):
    """
    Drop các cột có tỷ lệ null > threshold (%)
    """

    # Tính % null theo cột
    null_percent = df.isnull().mean() *100

    # In ra để kiểm tra
    print("Tỷ lệ null theo cột:")
    print(null_percent.sort_values(ascending=False))

    # Lấy danh sách cột cần drop
    cols_to_drop = null_percent[null_percent > threshold].index

    print(f"\nCác cột bị drop (> {threshold}% null):")
    print(list(cols_to_drop))

    # Drop cột
    df = df.drop(columns=cols_to_drop)

    return df

ahrf_silver_2020 = drop_high_null_columns(df_silver_2020)

ahrf_silver_2021 = drop_high_null_columns(df_silver_2021)

ahrf_silver_2022 = drop_high_null_columns(df_silver_2022)

ahrf_silver_2023 = drop_high_null_columns(df_silver_2023)

ahrf_silver_2024 = drop_high_null_columns(df_silver_2024)

ahrf_silver_2025 = drop_high_null_columns(df_silver_2025)

"""ĐẨY LÊN SILVER"""

#!pip install gcsfs pyarrow

from google.colab import auth
auth.authenticate_user()

from google.cloud import storage

client = storage.Client()
bucket = client.bucket("project-8e2366a6-d3cc-40ee-9de-silver-curated-dev")

def bronze_to_silver(df, local_file, gcs_path):

    # save parquet
    df.to_parquet(local_file, index=False)

    # upload
    blob = bucket.blob(gcs_path)
    blob.upload_from_filename(local_file)

    print(f"Uploaded to gs://data-silver/{gcs_path}")

#đẩy ahrf lên silver
datasets = [
    (
        ahrf_silver_2020,
        "ahrf_silver_2020.parquet",
        "ahrf/hospital_resources/ahrf_silver_2020.parquet"
    ),

    (
        ahrf_silver_2021,
        "ahrf_silver_2021.parquet",
        "ahrf/hospital_resources/ahrf_silver_2021.parquet"
    ),
    (
        ahrf_silver_2022,
        "ahrf_silver_2022.parquet",
        "ahrf/hospital_resources/ahrf_silver_2022.parquet"
    ),
    (
         ahrf_silver_2023,
         "ahrf_silver_2023.parquet",
         "ahrf/hospital_resources/ahrf_silver_2023.parquet"
     ),

     (
         ahrf_silver_2024,
         "ahrf_silver_2024.parquet",
         "ahrf/hospital_resources/ahrf_silver_2024.parquet"
     ),
     (
         ahrf_silver_2025,
         "ahrf_silver_2025.parquet",
         "ahrf/hospital_resources/ahrf_silver_2025.parquet"
     )
 ]

for df, local_file, gcs_path in datasets:
    bronze_to_silver(df, local_file, gcs_path)