# -*- coding: utf-8 -*-
"""ETL_bigdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzLMij6FOB026WO6lQa2owFOCQVCwMWF
"""

!apt-get install openjdk-11-jdk-headless -qq > /dev/null

!pip install pyspark

from google.colab import auth
auth.authenticate_user()

import google.auth

credentials, project_id = google.auth.default()

print(project_id)

PROJECT_ID = "project-8e2366a6-d3cc-40ee-9de"

from google.cloud import storage

client = storage.Client(project=PROJECT_ID)

buckets = list(client.list_buckets())

for b in buckets:
    print(b.name)

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("HospitalETL") \
    .config(
        "spark.jars.packages",
        "com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.5"
    ) \
    .config(
        "spark.hadoop.google.cloud.project.id",
        PROJECT_ID
    ) \
    .config(
        "spark.hadoop.fs.gs.impl",
        "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    ) \
    .config(
        "spark.hadoop.fs.AbstractFileSystem.gs.impl",
        "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    ) \
    .getOrCreate()

from pyspark.sql.functions import (
    col,
    trim,
    upper,
    current_timestamp,
    lit,
    when,
    to_date
)

from pyspark.sql.types import (
    IntegerType,
    FloatType
)

from google.cloud import storage
client = storage.Client()

bucket = client.bucket(
    "project-8e2366a6-d3cc-40ee-9de-bronze-raw-dev"
)
blobs = bucket.list_blobs(
    prefix="cms/pos/"
)

parquet_files = [

    blob.name

    for blob in blobs

    if blob.name.endswith(".parquet")
]

for f in parquet_files[:5]:
    print(f)

silver_path = (
    "gs://project-8e2366a6-d3cc-40ee-9de-silver-curated-dev/"
    "cms/pos/"
)

import re

for file_path in parquet_files:

    # =====================================
    # extract year + quarter
    # =====================================

    match = re.search(
        r"cms_pos_(q[1-4])_(\d{4})",
        file_path
    )

    if not match:
        print(f"Skip invalid filename: {file_path}")
        continue

    quarter = match.group(1).upper()
    year = int(match.group(2))

    print(f"\nProcessing {year} {quarter}")

    # =====================================
    # read bronze parquet
    # =====================================

    gcs_path = (
        "gs://project-8e2366a6-d3cc-40ee-9de-bronze-raw-dev/"
        + file_path
    )

    df_raw = spark.read.parquet(gcs_path)

    print(f"Raw rows: {df_raw.count()}")

    # =====================================
    # ETL
    # =====================================

    df_silver = (

        df_raw

        .select(

            col("PRVDR_NUM").alias("provider_id"),

            col("FAC_NAME").alias("facility_name"),

            col("CITY_NAME").alias("city"),

            col("STATE_CD").alias("state"),

            col("ZIP_CD").alias("zip_code"),

            col("FIPS_CNTY_CD").alias(
                "fips_county_code"
            ),

            col("CRTFD_BED_CNT").alias(
                "certified_bed_count"
            ),

            col("GNRL_FAC_TYPE_CD").alias(
                "facility_type_code"
            )
        )
    )

    # =====================================
    # clean text
    # =====================================

    TEXT_COLS = [

        "facility_name",
        "city",
        "state"
    ]

    for c in TEXT_COLS:

        df_silver = df_silver.withColumn(
            c,
            upper(trim(col(c)))
        )

    # =====================================
    # cast datatype
    # =====================================

    df_silver = df_silver.withColumn(

    "certified_bed_count",

    when(
        trim(col("certified_bed_count")) == "",
        None
    )

    .otherwise(
        col("certified_bed_count")
    )

    .cast(IntegerType())
)

    # =====================================
    # dedup
    # =====================================

    df_silver = df_silver.dropDuplicates()

    # =====================================
    # metadata
    # =====================================

    df_silver = (

        df_silver

        .withColumn(
            "_source",
            lit("cms_pos")
        )

        .withColumn(
            "_processed_at",
            current_timestamp()
        )

        .withColumn(
            "year",
            lit(year)
        )

        .withColumn(
            "quarter",
            lit(str(quarter))
        )
    )

    # =====================================
    # repartition
    # =====================================

    df_silver = df_silver.repartition(
        "year",
        "quarter"
    )

    print(f"Silver rows: {df_silver.count()}")

    # =====================================
    # write silver
    # =====================================

    (
        df_silver

        .write

        .mode("append")

        .partitionBy("year", "quarter")

        .parquet(silver_path)
    )

    print(f"Done {year} {quarter}")

df_silver.printSchema()

"""## **ETL HHS Capacity → df_hhs_silver** ##"""

hhs_path = "gs://project-8e2366a6-d3cc-40ee-9de-bronze-raw-dev/hhs/hospital_capacity/hhs_capacity.parquet"

df_hhs_raw = spark.read.parquet(hhs_path)

df_hhs_raw.columns

df_hhs = df_hhs_raw.select(
      # =========================
    # identifiers
    # =========================

    col("hospital_pk").alias("provider_id"),

    col("ccn"),

    # =========================
    # facility info
    # =========================

    col("hospital_name").alias("facility_name"),

    col("address"),

    col("city"),

    col("state"),

    col("zip").alias("zip_code"),

    col("fips_code").alias("fips_county_code"),

    col("hospital_subtype"),

    col("is_metro_micro"),

    # =========================
    # date
    # =========================

    col("collection_week").alias("report_date"),

    # =========================
    # inpatient metrics
    # =========================

    col("total_beds_7_day_avg").alias(
        "inpatient_beds_total"
    ),

    col("inpatient_beds_used_7_day_avg").alias(
        "inpatient_beds_used"
    ),

    # =========================
    # ICU metrics
    # =========================

    col("total_icu_beds_7_day_avg").alias(
        "icu_beds_total"
    ),

    col("icu_beds_used_7_day_avg").alias(
        "icu_beds_used"
    ),

    # =========================
    # COVID metrics
    # =========================

    col(
        "total_adult_patients_hospitalized_confirmed_covid_7_day_avg"
    ).alias(
        "covid_inpatient_count"
    ),

    col(
        "staffed_icu_adult_patients_confirmed_covid_7_day_avg"
    ).alias(
        "covid_icu_count"
    ),

    # =========================
    # quarantine metadata
    # =========================

    col("_validation_errors")
)

TEXT_COLS = [
    "facility_name",
    "address",
    "city",
    "state",
    "hospital_subtype"
]

for c in TEXT_COLS:

    df_hhs = df_hhs.withColumn(
        c,
        upper(trim(col(c)))
    )

df_hhs = df_hhs.withColumn(
    "report_date",
    to_date(col("report_date"))
)

FLOAT_COLS = [

    "inpatient_beds_total",
    "inpatient_beds_used",

    "icu_beds_total",
    "icu_beds_used",

    "covid_inpatient_count",
    "covid_icu_count"
]

for c in FLOAT_COLS:

    df_hhs = df_hhs.withColumn(
        c,
        col(c).cast(FloatType())
    )

## tính occupancy_rate
df_hhs = df_hhs.withColumn(

    "occupancy_rate",

    when(
        col("inpatient_beds_total") > 0,

        col("inpatient_beds_used") /
        col("inpatient_beds_total")
    ).otherwise(None)
)

df_hhs = df_hhs.withColumn(

    "icu_occupancy_rate",

    when(
        col("icu_beds_total") > 0,

        col("icu_beds_used") /
        col("icu_beds_total")
    ).otherwise(None)
)

df_hhs = df_hhs.withColumn(
    "_source",
    lit("hhs_capacity")
)

df_hhs = df_hhs.withColumn(
    "_processed_at",
    current_timestamp()
)

df_hhs_silver = df_hhs.dropDuplicates(
    ["provider_id", "report_date"]
)

df_hhs_silver = df_hhs_silver.select(

    "provider_id",
    "ccn",

    "facility_name",

    "address",
    "city",
    "state",

    "zip_code",
    "fips_county_code",

    "hospital_subtype",
    "is_metro_micro",

    "report_date",

    "inpatient_beds_total",
    "inpatient_beds_used",

    "icu_beds_total",
    "icu_beds_used",

    "occupancy_rate",
    "icu_occupancy_rate",

    "covid_inpatient_count",
    "covid_icu_count",

    "_source",
    "_processed_at"
)

df_hhs_silver.printSchema()

df_hhs_silver.show(5, truncate=False)

from pyspark.sql.functions import *

from pyspark.sql.functions import year, quarter

df_hhs_silver = df_hhs_silver.withColumn(
    "year",
    year("report_date")
)

df_hhs_silver = df_hhs_silver.withColumn(
    "quarter",
    quarter("report_date")
)

df_hhs_silver.select(
    "report_date",
    "year",
    "quarter"
).show(5)

hhs_silver_path = (
    "gs://project-8e2366a6-d3cc-40ee-9de-silver-curated-dev/"
    "hhs/hospital_capacity/"
)

df_hhs_silver.write \
    .mode("overwrite") \
    .partitionBy("year", "quarter") \
    .parquet(hhs_silver_path)