# -*- coding: utf-8 -*-
"""ingestion_bronze.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGBwYKKMd-eLSeVov1DDZ9AhXk_Ze6fU
"""

from google.colab import auth
auth.authenticate_user()

!pip -q install pandas pyarrow fastparquet gcsfs google-cloud-storage requests

from google.cloud import storage

PROJECT_ID = "project-8e2366a6-d3cc-40ee-9de"

BUCKET_NAME = "project-8e2366a6-d3cc-40ee-9de-bronze-raw-dev"

"""### **Ingestion POS: danh sách cơ sở y tế được chứng nhận Medicare**"""

import requests
import pandas as pd

CMS_POS_URL = (
    "https://data.cms.gov/data-api/v1/dataset/"
    "8f6da2b1-f719-40c2-8f73-2b7ecb7fb42a/data"  ## mã id của từng quý, cập nhật để lấy hết bộ dữ liệu
)

response = requests.get(
    CMS_POS_URL,
    params={
        "limit": 500000
    }
)

data = response.json()

df_pos = pd.DataFrame(data)

print(df_pos.shape)
df_pos.head()

## chuyển đổi csv sang parquet để đẩy lên gcs
import os

os.makedirs("data", exist_ok=True)

pos_parquet_path = "data/cms_pos.parquet"

df_pos.to_parquet(
    pos_parquet_path,
    engine="pyarrow",
    index=False
)

print("Saved:", pos_parquet_path)

## đẩy lên gcs

client = storage.Client(project=PROJECT_ID)

bucket = client.bucket(BUCKET_NAME)

blob = bucket.blob(
    "cms/pos/cms_pos_q1_2020.parquet"
)
blob.upload_from_filename(pos_parquet_path)

print("Uploaded POS parquet to GCS")

import pandas as pd

# 1. Xem thử 5 dòng đầu
print(df_pos.head())

# 2. Xem tổng quan về các cột và kiểu dữ liệu
print(df_pos.info())

# 3. Thống kê nhanh cho các cột số
print(df_pos.describe())

# 4. Đếm số lượng nhà cung cấp theo từng bang
print(df_pos['STATE_CD'].value_counts())

# 5. Lọc ra các cơ sở đã chấm dứt hoạt động
df_terminated = df_pos[df_pos['TRMNTN_EXPRTN_DT'].notna()]
print(f"Số cơ sở đã chấm dứt: {len(df_terminated)}")

"""### **Ingestion data từ HHS: COVID-19 Reported Patient Impact and Hospital Capacity by State (RAW)**
Thời gian: tháng 01/2020 đến tháng 05/2024.

"""

!pip install sodapy

import pandas as pd
import matplotlib.pyplot as plt
from sodapy import Socrata

client = Socrata(
    "healthdata.gov",
    None
)
DATASET_ID = "anag-cw7u"
results = client.get(
    DATASET_ID,
    limit=50000
)

df_hhs = pd.DataFrame.from_records(results)
# HHS_URL = "https://healthdata.gov/resource/6xf2-c3ie.csv"

# df_hhs = pd.read_csv(
#     HHS_URL
# )

print(df_hhs.shape)
print("Ngày bắt đầu:", df_hhs['collection_week'].min())
print("Ngày kết thúc:", df_hhs['collection_week'].max())
df_hhs.head()

print(list(df_hhs.columns))

KEEP_COLS = [
    "hospital_pk",
    "collection_week",
    "state",
    "ccn",
    "hospital_name",
    "address",
    "city",
    "zip",
    "hospital_subtype",
    "fips_code",
    "is_metro_micro",

    "total_beds_7_day_avg",
    "all_adult_hospital_beds_7_day_avg",
    "all_adult_hospital_inpatient_beds_7_day_avg",
    "inpatient_beds_used_7_day_avg",
    "all_adult_hospital_inpatient_bed_occupied_7_day_avg",
    "inpatient_beds_used_covid_7_day_avg",

    "total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg",
    "total_adult_patients_hospitalized_confirmed_covid_7_day_avg",

    "total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg",
    "total_pediatric_patients_hospitalized_confirmed_covid_7_day_avg",

    "inpatient_beds_7_day_avg",
    "total_icu_beds_7_day_avg",
    "total_staffed_adult_icu_beds_7_day_avg",
    "icu_beds_used_7_day_avg",
    "staffed_adult_icu_bed_occupancy_7_day_avg",

    "staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg",
    "staffed_icu_adult_patients_confirmed_covid_7_day_avg",

    "total_patients_hospitalized_confirmed_influenza_7_day_avg",
    "icu_patients_confirmed_influenza_7_day_avg",

    "previous_day_admission_adult_covid_confirmed_7_day_sum",
    "previous_day_admission_pediatric_covid_confirmed_7_day_sum",
    "previous_day_total_ed_visits_7_day_sum",

    "geocoded_hospital_address",
    "hhs_ids",

    "is_corrected",

    "all_pediatric_inpatient_bed_occupied_7_day_avg",
    "all_pediatric_inpatient_beds_7_day_avg",

    "staffed_pediatric_icu_bed_occupancy_7_day_avg",

    "total_staffed_pediatric_icu_beds_7_day_avg",

    "staffed_icu_pediatric_patients_confirmed_covid_7_day_avg",

    "previous_week_personnel_covid_vaccinated_doses_administered_7_day",

    "total_personnel_covid_vaccinated_doses_none_7_day",
    "total_personnel_covid_vaccinated_doses_one_7_day",
    "total_personnel_covid_vaccinated_doses_all_7_day",

    "previous_week_patients_covid_vaccinated_doses_one_7_day",
    "previous_week_patients_covid_vaccinated_doses_all_7_day"

]
df_hhs = df_hhs[KEEP_COLS]

from dataclasses import dataclass
from typing import List
from datetime import datetime
from dataclasses import dataclass
from typing import List

@dataclass
class ValidationResult:
    passed: bool
    errors: List[str]
    warnings: List[str]

def validate_hhs_rows(df: pd.DataFrame):

    df = df.copy()

    errors_col = []

    required_cols = [
        "hospital_pk",
        "state",
        "collection_week"
    ]

    numeric_cols = [
        "inpatient_beds_7_day_avg",
        "total_icu_beds_7_day_avg",
        "inpatient_beds_used_7_day_avg"
    ]

    for idx, row in df.iterrows():

        row_errors = []

        # ====================================
        # Rule 1: Required columns not null
        # ====================================

        for col in required_cols:

            if col not in df.columns:
                row_errors.append(f"missing_column:{col}")

            elif pd.isna(row[col]):

                row_errors.append(f"null:{col}")

        # ====================================
        # Rule 2: Numeric columns >= 0
        # ====================================

        for col in numeric_cols:

            if col in df.columns:

                val = pd.to_numeric(
                    row[col],
                    errors="coerce"
                )

                if pd.notna(val) and val < 0:

                    row_errors.append(f"negative:{col}")

        errors_col.append(row_errors)

    df["_validation_errors"] = errors_col

    # valid rows
    valid_df = df[
        df["_validation_errors"].str.len() == 0
    ].copy()

    # invalid rows
    invalid_df = df[
        df["_validation_errors"].str.len() > 0
    ].copy()

    return valid_df, invalid_df

valid_df, invalid_df = validate_hhs_rows(df_hhs)
print("VALID:", len(valid_df))
print("INVALID:", len(invalid_df))
invalid_df[
    [
        "hospital_pk",
        "_validation_errors"
    ]
].head()

valid_parquet_path = "data/hhs_capacity_valid.parquet"

invalid_parquet_path = "data/hhs_capacity_invalid.parquet"

valid_df.to_parquet(
    valid_parquet_path,
    engine="pyarrow",
    index=False
)

valid_blob = bucket.blob(
    f"hhs/hospital_capacity/hhs_capacity.parquet"
)

valid_blob.upload_from_filename(
    valid_parquet_path
)

print("Uploaded VALID parquet")

quarantine_bucket = client.bucket(
    "project-8e2366a6-d3cc-40ee-9de-quarantine-dev"
)
invalid_blob = quarantine_bucket.blob(
    f"hhs/hospital_capacity/hhs_capacity_invalid.parquet"
)
invalid_df.to_parquet(
    invalid_parquet_path,
    engine="pyarrow",
    index=False
)
invalid_blob.upload_from_filename(
    invalid_parquet_path
)

print("Uploaded INVALID parquet")

"""### Step: ETL ###
**Chuyển sang notebook mới**

"""